document.addEventListener('DOMContentLoaded',()=>{
const app=window.CCAM_APP_DATA||{};
const DEFAULT_ARTICLES=[
{id:'convention-dentaire-2023-2028',title:"Convention dentaire 2023-2028 : ce qu'il faut retenir",date:'2026-04-26',source:'Ameli',category:'Dentaire',summary:"Synthèse pratique sur la convention dentaire, les mesures conventionnelles et les points à contrôler pour les actes bucco-dentaires.",codes:['HBLD031','HBLD032','HBLD033','HBLD035','HBLD038','HBKD140','HBKD212'],content_html:'<p>Ce dossier présente les points utiles à retenir autour de la convention dentaire 2023-2028. Il sert d’aide à la lecture pour relier les mesures conventionnelles aux actes CCAM, aux paniers de soins et aux vérifications de facturation.</p><h2>À retenir</h2><ul><li>Les mesures conventionnelles doivent être rapprochées des actes CCAM et des tarifs applicables.</li><li>Les actes prothétiques nécessitent une attention particulière sur le panier de soins : RAC 0, tarif maîtrisé ou tarif libre.</li><li>Les contextes patient peuvent modifier la lecture du remboursement : C2S, ALD, régime local, maternité ou AT/MP.</li><li>Le paramétrage doit toujours être vérifié avec la source officielle et le contexte réel de facturation.</li></ul><h2>Impact pratique</h2><p>Pour un centre de santé ou un logiciel métier, l’intérêt est de contrôler les codes, l’activité, la phase, la BRSS, le panier de soins et les éventuelles limites d’honoraires.</p>'},
{id:'cent-pour-cent-sante-dentaire',title:'100 % Santé dentaire : actes, matériaux et paniers de soins',date:'2026-04-26',source:'Ameli',category:'100 % Santé',summary:"Décryptage des paniers 100 % Santé, RAC modéré et tarif libre pour mieux comprendre le classement des actes dentaires.",codes:['HBLD031','HBLD033','HBLD090','HBLD101','HBLD203','HBLD490'],content_html:'<p>Le 100 % Santé dentaire concerne principalement les prothèses dentaires : couronnes, bridges et prothèses amovibles. Les actes doivent être lus avec leur matériau, leur localisation et leur panier de soins.</p><h2>À retenir</h2><ul><li>Un code peut appartenir au panier RAC 0, au tarif maîtrisé ou au tarif libre selon les règles applicables.</li><li>Les matériaux et la localisation de la dent peuvent influencer le classement.</li><li>La simple présence d’un acte dentaire ne suffit pas toujours à conclure : le contexte clinique et réglementaire reste nécessaire.</li></ul><h2>Impact pratique</h2><p>Sur les fiches actes, il est utile d’afficher clairement la catégorie du panier, le niveau de certitude et la justification de classement.</p>'},
{id:'tarifs-dentaires',title:'Tarifs conventionnels dentaires : repères pratiques',date:'2026-04-26',source:'Ameli',category:'Tarifs',summary:"Repères de lecture sur les tarifs conventionnels, BRSS, honoraires limites et estimations AMO.",codes:['HBKD140','HBLD040','HBLD043','HBLD073','HBLD131'],content_html:'<p>Les tarifs conventionnels permettent de rapprocher un acte CCAM de sa base de remboursement et, lorsqu’il y a lieu, de ses honoraires limites.</p><h2>À retenir</h2><ul><li>La BRSS sert de base au calcul indicatif du remboursement AMO.</li><li>Les honoraires limites concernent surtout certains actes encadrés.</li><li>Le taux affiché dans l’annuaire est une aide standard et doit être ajusté selon le contexte patient.</li></ul><h2>Impact pratique</h2><p>L’export CSV facilite le contrôle des colonnes utiles : code, activité, phase, libellé, BRSS, taux, montant AMO et panier.</p>'},
{id:'codage-ccam-medecins',title:'Codage CCAM : retrouver et contrôler les actes médicaux',date:'2026-04-26',source:'Ameli',category:'CCAM',summary:"Méthode de lecture pour rechercher un acte CCAM, vérifier son code et comprendre les informations affichées.",codes:[],content_html:'<p>La CCAM structure les actes techniques avec un code, une activité, une phase, un libellé et des informations tarifaires. L’annuaire permet de retrouver rapidement ces éléments.</p><h2>À retenir</h2><ul><li>Le couple code + activité + phase est important pour éviter les confusions.</li><li>Le libellé doit être lu attentivement, notamment en cas d’actes proches.</li><li>La classification médicale ou bucco-dentaire est une aide de lecture, pas une décision réglementaire autonome.</li></ul><h2>Impact pratique</h2><p>La recherche par code ou libellé aide à contrôler un paramétrage, préparer une correction ou documenter une question de facturation.</p>'}
];
const articles=(Array.isArray(app.articles)&&app.articles.length)?app.articles:DEFAULT_ARTICLES;
const list=document.getElementById('articles');const body=document.getElementById('articleBody');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
if(list){list.innerHTML=articles.map(a=>`<article class="card newsitem"><span class="pill p-med">${esc(a.category||a.tag||'Dossier')}</span><h3><a href="article.html?id=${encodeURIComponent(a.id)}">${esc(a.title)}</a></h3><p>${esc(a.summary||'')}</p><p class="small">${esc(a.source||'Source')} · ${new Date(a.date).toLocaleDateString('fr-FR')} · ${Number((a.codes||[]).length).toLocaleString('fr-FR')} code(s) lié(s)</p></article>`).join('')}
if(body){const id=new URLSearchParams(location.search).get('id');const a=articles.find(x=>x.id===id)||articles[0];if(!a){body.innerHTML='<div class="note">Dossier introuvable.</div>';return}document.title=a.title+' — Annuaire CCAM Santé';document.getElementById('articleTag').textContent=a.category||a.tag||'Dossier';document.getElementById('articleTitle').textContent=a.title;document.getElementById('articleSummary').textContent=a.summary||'';body.innerHTML=a.content_html||'<p>Aucun contenu disponible.</p>';const codes=(a.codes||[]).slice(0,120);document.getElementById('articleCodes').innerHTML=codes.length?codes.map(c=>`<a class="pill p-out" style="margin:4px" href="acte.html?code=${encodeURIComponent(c)}">${esc(c)}</a>`).join(''):'Aucun code précis lié dans ce dossier.'}
});
